# Least Response Time (somente NGINX Plus)
events {}

http {
    upstream app {
        # ATENÇÃO: least_time só existe no NGINX Plus (comercial).
        least_time header;
        server host.docker.internal:3001;
        server host.docker.internal:3002;
        server host.docker.internal:3003;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Upstream $upstream_addr always;
        }
    }
}
