# Weighted Round Robin: server-1 recebe 5/9, server-2 3/9, server-3 1/9

events {}
http {
    upstream app {
        server host.docker.internal:3001 weight=5;
        server host.docker.internal:3002 weight=3;
        server host.docker.internal:3003 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Upstream $upstream_addr always;
        }
    }
}
